language: python
branches:
  only:
  - master
install:
- pip install "pelican[markdown]"
- git clone --recursive https://github.com/getpelican/pelican-themes ~/pelican-themes
- pelican-themes --install ~/pelican-themes/brutalist
script:
- make html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
